"""course benefits

Revision ID: a80cb6606333
Revises: e52d9ddd8ca4
Create Date: 2026-08-29 23:18:19.927949
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "a80cb6606333"
down_revision: str | None = "e52d9ddd8ca4"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "course_benefits",
        sa.Column("course_id", sa.UUID(), nullable=False),
        sa.Column("position", sa.Integer(), nullable=False),
        sa.Column("title", sa.String(length=120), nullable=False),
        sa.Column("text", sa.Text(), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["course_id"], ["courses.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_course_benefits_course_id"), "course_benefits", ["course_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_course_benefits_course_id"), table_name="course_benefits")
    op.drop_table("course_benefits")
    # ### end Alembic commands ###
