"""course syllabus, progress, reviews and questions

Revision ID: e52d9ddd8ca4
Revises: 8b1c7d2e4a90
Create Date: 2026-08-29 21:08:55.828471
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "e52d9ddd8ca4"
down_revision: str | None = "8b1c7d2e4a90"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "course_questions",
        sa.Column("course_id", sa.UUID(), nullable=False),
        sa.Column("position", sa.Integer(), nullable=False),
        sa.Column("question", sa.String(length=300), nullable=False),
        sa.Column("answer", sa.Text(), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["course_id"], ["courses.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_course_questions_course_id"), "course_questions", ["course_id"], unique=False
    )
    op.create_table(
        "course_units",
        sa.Column("course_id", sa.UUID(), nullable=False),
        sa.Column(
            "kind",
            sa.Enum(
                "MODULE",
                "ASSIGNMENT",
                "TEST",
                name="course_unit_kind",
                native_enum=False,
                length=20,
            ),
            nullable=False,
        ),
        sa.Column("position", sa.Integer(), nullable=False),
        sa.Column("title", sa.String(length=200), nullable=False),
        sa.Column("summary", sa.String(length=300), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["course_id"], ["courses.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("course_id", "kind", "position", name="uq_unit_position"),
    )
    op.create_index(op.f("ix_course_units_course_id"), "course_units", ["course_id"], unique=False)
    op.create_index(op.f("ix_course_units_kind"), "course_units", ["kind"], unique=False)
    op.create_table(
        "reviews",
        sa.Column("course_id", sa.UUID(), nullable=False),
        sa.Column("author_id", sa.UUID(), nullable=False),
        sa.Column("rating", sa.Integer(), nullable=False),
        sa.Column("text", sa.Text(), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["author_id"], ["users.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["course_id"], ["courses.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_reviews_author_id"), "reviews", ["author_id"], unique=False)
    op.create_index(op.f("ix_reviews_course_id"), "reviews", ["course_id"], unique=False)
    op.create_table(
        "unit_progress",
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("unit_id", sa.UUID(), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "NOT_STARTED",
                "IN_PROGRESS",
                "DONE",
                name="unit_status",
                native_enum=False,
                length=20,
            ),
            nullable=False,
        ),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["unit_id"], ["course_units.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("user_id", "unit_id", name="uq_progress_user_unit"),
    )
    op.create_index(op.f("ix_unit_progress_unit_id"), "unit_progress", ["unit_id"], unique=False)
    op.create_index(op.f("ix_unit_progress_user_id"), "unit_progress", ["user_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_unit_progress_user_id"), table_name="unit_progress")
    op.drop_index(op.f("ix_unit_progress_unit_id"), table_name="unit_progress")
    op.drop_table("unit_progress")
    op.drop_index(op.f("ix_reviews_course_id"), table_name="reviews")
    op.drop_index(op.f("ix_reviews_author_id"), table_name="reviews")
    op.drop_table("reviews")
    op.drop_index(op.f("ix_course_units_kind"), table_name="course_units")
    op.drop_index(op.f("ix_course_units_course_id"), table_name="course_units")
    op.drop_table("course_units")
    op.drop_index(op.f("ix_course_questions_course_id"), table_name="course_questions")
    op.drop_table("course_questions")
    # ### end Alembic commands ###
